server:
  port: 8081
app:
  name: MessBoard
spring:
  h2:
    console:
      enabled: true
  datasource:
    username: root
    password: root
    url: jdbc:h2:file:./src/main/resources/data/MessBoardDb;AUTO_SERVER=true
  jpa:
    hibernate:
      ddl-auto: create-drop #nejlepší je validate

